

--AVG LENGTH OF STAY
SELECT AVG(LENGTH_OF_STAY) AS AVG_STAY
FROM HEALTHCARE_DATA02;

--MONTHLY PATIENT ADMISSION TREND
SELECT FORMAT(DATE_OF_ADMISSION, 'yyyy-MM') AS MONTH,
       COUNT(*) AS TOTAL_ADMISSIONS
FROM HEALTHCARE_DATA02
GROUP BY FORMAT(DATE_OF_ADMISSION, 'yyyy-MM')
ORDER BY MONTH;

--MONTHLY PATIENT DISCHARGE TREND
SELECT FORMAT(DISCHARGE_DATE, 'yyyy-MM') AS MONTH,
       COUNT(*) AS TOTAL_DISCHARGE
FROM HEALTHCARE_DATA02
GROUP BY FORMAT(DISCHARGE_DATE, 'yyyy-MM')
ORDER BY MONTH;

--PATIENTS STAYED MORE THEN AVG LENGTH OF STAY
SELECT * FROM HEALTHCARE_DATA02
WHERE LENGTH_OF_STAY > (SELECT AVG(LENGTH_OF_STAY) FROM HEALTHCARE_DATA02);