
--DATA CLEANING

--1. CHECK NULL VALUES

SELECT 
COUNT(*) AS TOTALROWS,
SUM(CASE WHEN NAME IS NULL THEN 1 ELSE 0 END) AS NULL_NAME,
SUM(CASE WHEN BILLING_AMOUNT IS NULL THEN 1 ELSE 0 END) AS NULL_BILLING
FROM HOSPITAL_DATA;

--2. FIND AND REMOVE DUPLICATES
SELECT NAME, DATE_OF_ADMISSION, DOCTOR, COUNT(*) AS DUPLICATE_COUNT
FROM HOSPITAL_DATA
GROUP BY NAME, DATE_OF_ADMISSION, DOCTOR
HAVING COUNT(*) > 1;

 --REMOVE DUPLICATE
WITH CTE AS (
     SELECT * , ROW_NUMBER() OVER(PARTITION BY  NAME, DATE_OF_ADMISSION, DOCTOR ORDER BY NAME) AS RN
     FROM HOSPITAL_DATA)

DELETE FROM CTE WHERE RN > 1; 

--CREATE DERIVED COLUMNS

--1. LENGTH OF STAY
ALTER TABLE HOSPITAL_DATA
ADD LENGTH_OF_STAY AS DATEDIFF(DAY, DATE_OF_ADMISSION, DISCHARGE_DATE);

--2. AGE GROUP
ALTER TABLE HOSPITAL_DATA
ADD AGE_GROUP AS 
CASE 
    WHEN AGE < 18 THEN 'CHILD'
    WHEN AGE BETWEEN 18 AND 35 THEN 'YOUNG ADULT'
    WHEN AGE BETWEEN 35 AND 55 THEN 'ADULT'
ELSE 'SENIOR'
END;
