

--TOTAL REVENUE
SELECT ROUND(SUM(BILLING_AMOUNT), 2) AS TOATL_REVENUE
FROM HEALTHCARE_DATA02;

--AVG BILLING
SELECT ROUND(AVG(BILLING_AMOUNT), 2) AS AVG_BILLING
FROM HEALTHCARE_DATA02;

--TOP PERFORMING HOSPITAL BY REVENUE
SELECT TOP 1 HOSPITAL, ROUND(SUM(BILLING_AMOUNT), 2) AS REVENUE
FROM HEALTHCARE_DATA02
GROUP BY HOSPITAL
ORDER BY REVENUE DESC;

--MONTHLY PATIENT ADMISSION TREND
SELECT FORMAT(DATE_OF_ADMISSION, 'yyyy-MM') AS MONTH,
       COUNT(*) AS TOTAL_ADMISSIONS
FROM HEALTHCARE_DATA02
GROUP BY FORMAT(DATE_OF_ADMISSION, 'yyyy-MM')
ORDER BY MONTH;

--RUNNING TOTAL OF REVENUE BY MONTH
WITH MONTHLY_REVENUE AS (
SELECT YEAR(DATE_OF_ADMISSION) AS YEAR,
       MONTH(DATE_OF_ADMISSION) AS MONTH,
       ROUND(SUM(BILLING_AMOUNT), 2) AS MONTHLY_REVENUE
FROM HEALTHCARE_DATA02
GROUP BY YEAR(DATE_OF_ADMISSION),
       MONTH(DATE_OF_ADMISSION)
)
SELECT YEAR,
       MONTH,
       MONTHLY_REVENUE,
       SUM(MONTHLY_REVENUE) OVER(ORDER BY YEAR, MONTH) AS RUNNING_TOTAL
FROM MONTHLY_REVENUE
ORDER BY YEAR, MONTH;
